on:
  push:
    branches:
      - master
jobs:   
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
        - name: install ssh keys
          run: |
              install -m 600 -D /dev/null ~/.ssh/id_rsa
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && ls -la && git checkout ${{ secrets.MASTER_BRANCH }} && git pull && exit"

        - name: Build clean project at Server
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && rm -rf node_modules/ && rm -rf package-lock.json && rm -rf dist/"

        - name: NPM
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -la && bash azimov.sh"
